apiVersion: v1
kind: Service
metadata:
  name: udp-service
spec:
  selector:
    app: udp-svc  # Replace with the appropriate selector for your application
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
