apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-for-postgresql-data
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain  # Adjust if needed
  storageClassName: local-storage
  volumeMode: Filesystem
  hostPath:
    path: /var/lib/postgresql/data/
