apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app.kubernetes.io/name: kafka  # Adjust the selector based on your Kafka pods' labels
  ports:
    - protocol: TCP
      port: 9092  # The port on the service
      targetPort: 9092  # The port on the pods
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-nodeport
spec:
  selector:
    app.kubernetes.io/name: kafka  # Adjust the selector based on your Kafka pods' labels
  ports:
    - protocol: TCP
      port: 9092  # The port on the service
      targetPort: 9092  # The port on the pods
  type: NodePort
