apiVersion: v1
kind: Service
metadata:
  name: kafka-service
spec:
  selector:
    app: kafka-svc  # Replace with the appropriate selector for your application
  ports:
    - protocol: TCP
      port: 9099
      targetPort: 9099
