apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  namespace: localregistry
  labels:
    run: docker-registry
spec:
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5113
      targetPort: 5000
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
